apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: ebs-dynamic 
spec: 
  storageClassName: "expense-ebs"
  volumeName: ebs-static
  accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 3Gi
---
apiVersion: v1 
kind: Pod 
metadata:
  name: ebs-dynamic
  labels:
    purpose: ebs-dynamic
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1a
  containers:
  - name: nginx 
    image: nginx 
    volumeMounts:
    - name: ebs-dynamic
      mountPath: /usr/share/nginx/html
  volumes: 
  - name: ebs-dynamic
    persistentVolumeClaim: 
      claimName: ebs-dynamic
---
apiVersion: v1 
kind: Service 
metadata:
  name: nginx 
spec: 
  type: LoadBalancer
  selector: 
    purpose: ebs-static
  ports:
  - name: nginx-svc-port 
    protocol: TCP
    port: 80
    targetPort: 80