apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  directoryPerms: "700"
  fileSystemId: fs-0b85c5652877f5318  # change with your fs id which is only one for entire project
  basePath: "/expense"