apiVersion: v1 
kind: Pod 
metadata: 
  name: pod-config
spec:
  containers:
  - name: nginx 
    image: nginx
    envFrom:
    - configMapRef:
        name: nginx-configl
    # env: 
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: nginx-config # name of the config map you are reffering to
    #       key: course # env.name and configmap key name can be different
    # - name: duration
    #   valueFrom:
    #     configMapKeyRef:
    #       name: nginx-config
    #       key: duration