apiVersion: v1 
pod: Pod 
metadata: 
  name: pod-config
spec:
  containers:
  - name: nginx 
    image: nginx
    env: 
    - name: course
      valueFrom:
        ConfigMapKeyRef:
        name: nginx-config # name of the config map you are reffering to
        key: course # env.name and configmap key name can be different
    - name: duration
      valueFrom:
        ConfigMapKeyRef:
        name: nginx-config
        key: duration