apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx
  labels: # these are replicaset labels
    app: nginx 
    tier: frontend
spec:
  replicas: 3 # modify replicas according to your requirement
  selector:
    matchLabels:  # these are used to select the pod to create replicas
      app: nginx
      tier: frontend
  template: # this is pod defination
    metadata:
      labels: # these labels belongs to pod
        app: nginx 
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1 
kind: Service 
metadata:
  name: nginx 
spec: 
  selector:
    app: frontend
    tier: nginx
  ports:
  - name: nginx-svc-port 
    protocol: TCP
    port: 80
    targetPort: 80 